proxy-groups:
  - name: ğŸš€ èµ·é£
    type: select
    proxies:
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯è´Ÿè½½å‡è¡¡
      -  ğŸ‡ºğŸ‡¸ ç¾å›½è´Ÿè½½å‡è¡¡
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾è´Ÿè½½å‡è¡¡
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è´Ÿè½½å‡è¡¡
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬è´Ÿè½½å‡è¡¡
      -  ğŸ‡°ğŸ‡· éŸ©å›½è´Ÿè½½å‡è¡¡
      - DIRECT
  - name: ğŸš€ æ‰‹åŠ¨1
    include-all: true
    filter: (?i).*
    type: select
  - name: ğŸš€ æ‰‹åŠ¨2
    include-all: true
    type: select
    filter: (?i).*
  - name: ğŸš€ æ‰‹åŠ¨3
    include-all: true
    type: select
    filter: (?i).*
  - name: ğŸµ TikTok
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: ğŸ“² Telegram
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: ğŸ“¹ YouTube
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
  - name: ğŸ’¬ OpenAi
    type: select
    proxies:
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: ğŸŒ Civitai
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯Bing
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: ğŸš© ç¤¾äº¤å¹³å°IPå½’å±åœ°
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
  - name: ğŸ“º Bilibili
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
  - name: ğŸ¥ Netflix
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      -  ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      -  ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      -  ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      -  ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
      -  ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      -  ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸ¯ å›½å†…æµé‡
    type: select
    proxies:
      - DIRECT
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸ›¡ï¸ éšç§é˜²æŠ¤
    type: select
    proxies:
      - REJECT
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ èµ·é£
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      -  ğŸš€ èµ·é£
      -  ğŸš€ è‡ªåŠ¨åˆ‡æ¢
      -  ğŸ¯ å›½å†…æµé‡
      -  ğŸš€ æ‰‹åŠ¨1
      -  ğŸš€ æ‰‹åŠ¨2
      -  ğŸš€ æ‰‹åŠ¨3
      - DIRECT
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¹ğŸ‡¼|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡°ğŸ‡·|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“).*$
    type: url-test
    interval: 30
    tolerance: 50
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¹ğŸ‡¼|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸ‡°ğŸ‡· éŸ©å›½è´Ÿè½½å‡è¡¡
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡°ğŸ‡·|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“).*$
    type: load-balance
    interval: 30
    tolerance: 50
  - name: ğŸš€ è‡ªåŠ¨åˆ‡æ¢
    include-all: true
    filter: ^.*(?!.*è‡ªæœ‰).*(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan|ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ğŸ‡¹ğŸ‡¼|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡°ğŸ‡·|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“).*$
    type: url-test
    interval: 30
    tolerance: 50
rule-providers:
  China:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml
    path: ./ruleset/China.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Youtube:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/Youtube.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  TikTok:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    path: ./ruleset/TikTok.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Telegram:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/Telegram.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Game:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    path: ./ruleset/Game.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  OpenAi:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/OpenAi.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Bing:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
    path: ./ruleset/Bing.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Copilot:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
    path: ./ruleset/Copilot.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  OneDrive:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
    path: ./ruleset/OneDrive.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Microsoft:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  rule-provider:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/master/generated/rule-provider.yaml
    path: ./ruleset/rule-provider.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Netflix:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical.yaml
    path: ./ruleset/Netflix.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Bilibili:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./ruleset/Bilibili.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Apple:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical.yaml
    path: ./ruleset/Apple.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  ChinaMedia:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
    path: ./ruleset/ChinaMedia.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Advertising:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    path: ./ruleset/Advertising.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Privacy:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml
    path: ./ruleset/Privacy.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
  Proxy:
    url: >-
      https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml
    path: ./ruleset/Proxy.yaml
    behavior: classical
    interval: 86400
    format: yaml
    type: http
    proxy: DIRECT
rules:
  - "DOMAIN-SUFFIX,adobe.io,REJECT"
  - "DOMAIN-SUFFIX,adobestats.io,REJECT"
  - "DOMAIN-SUFFIX,oracle.com,DIRECT"
  - "DOMAIN-SUFFIX,oraclecloud.com,DIRECT"
  - "DOMAIN-SUFFIX,civitai.com,ğŸŒ Civitai"
  - "RULE-SET,Youtube,ğŸ“¹ YouTube"
  - "RULE-SET,TikTok,ğŸµ TikTok"
  - "RULE-SET,Telegram,ğŸ“² Telegram"
  - "RULE-SET,OpenAi,ğŸ’¬ OpenAi"
  - "RULE-SET,Bing,â“‚ï¸ å¾®è½¯Bing"
  - "RULE-SET,Copilot,â“‚ï¸ å¾®è½¯Bing"
  - "RULE-SET,OneDrive,â“‚ï¸ å¾®è½¯äº‘ç›˜"
  - "RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡"
  - "RULE-SET,Game,ğŸ® æ¸¸æˆå¹³å°"
  - "RULE-SET,China,ğŸ¯ å›½å†…æµé‡"
  - "GEOIP,CN,ğŸ¯ å›½å†…æµé‡"
  - "RULE-SET,rule-provider,ğŸš© ç¤¾äº¤å¹³å°IPå½’å±åœ°"
  - "RULE-SET,Netflix,ğŸ¥ Netflix"
  - "RULE-SET,Bilibili,ğŸ“º Bilibili"
  - "RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡"
  - "RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“"
  - "RULE-SET,Advertising,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
  - "RULE-SET,Privacy,ğŸ›¡ï¸ éšç§é˜²æŠ¤"
  - "RULE-SET,Proxy,ğŸš€ èµ·é£"
  - "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼"
